name: Manual Compile

on:
  workflow_dispatch:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.5
      - name: Install Dependencies
        run: npm ci
      - name: Build 🗜️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          if ! git diff --quiet; then
            git config --global user.email "<>"
            git config --global user.name "GitHub Actions"
            git commit -am "manual build"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/coffeelint/coffeelint.github.io.git" HEAD:master
          else
            echo "Nothing to commit"
          fi
