name: PR

on:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Install Dependencies
        run: npm ci
      - name: Build 🗜️
        run: npm run build
